using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum MessageID
{
	GAME_START,         
	GAME_PAUSE,         
	GAME_RESUME,        
	GAME_RETRY,         
	GAME_INFO_UPDATE,   
	GAME_WIN,           
	GAME_OVER,          
	ENEMY_SPAWN,        
	ENEMY_BORN,         
	ENEMY_DIE,          
	PLAYER_SPAWN,       
	PLAYER_BORN,        
	PLAYER_DIE,         
	BONUS_SPAWN,        
	BONUS_BOOM_TRIGGER, 
	BONUS_SHIELD_TRIGGER,   
	BONUS_TANK_TRIGGER,     
	BONUS_LEVEL_TRIGGER,    
	BONUS_STOP_WATCH_TRIGGER,   
	BONUS_SHOVEL_TRIGGER,   
	MOBILE_MOVE_INPUT,      
	MOBILE_FIRE_INPUT,      
	HOME_DESTROY,           
	DATA_GAME_START,        
	DATA_ENEMY_SPAWN,       
	DATA_ENEMY_DIE,         
	DATA_PLAYER_SPAWN,      
	DATA_PLAYER_DIE,        
	DATA_BONUS_TANK,        
	START_LEVEL,            
	DATA_START_LEVEL,       
	LEVEL_WIN,              
	DATA_LEVEL_WIN,         
	ENEMY_CRIZY,            
}
